version: "3.9"
services:
  pipedrive-task-service:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
      - 3001:3001
    environment:
      NODE_ENV: development
      HTTP_PORT: 3000
      DEBUG_PORT: 3001
    restart: unless-stopped
    volumes:
      - .:/app/
    networks:
      - pipedrive

networks:
  pipedrive:
    driver: bridge
